Align from Develop (#15)
* DictionaryHelper - Test WIP
* New String  Method ToInt32
* method ToInt32 modified with CulureInfo as input value - default is currentculture
* Fixed StringTest
* Create nuget.config
* Update dotnetcore.yml
* Update version.json

Co-authored-by: VforValerioB <52419917+VforValerioB@users.noreply.github.com>

diff --git a/.github/workflows/dotnetcore.yml b/.github/workflows/dotnetcore.yml
--- a/.github/workflows/dotnetcore.yml
+++ b/.github/workflows/dotnetcore.yml
@@ -32,7 +32,28 @@ jobs:
       run: dotnet pack ./SharpHelpers/SharpHelpers.sln -c Release --no-build
 
     - name: setup nuget
-      if: github.event_name == 'push' && github.ref == 'refs/heads/master'
+      if: github.event_name == 'push' && github.ref == 'refs/heads/develop'
       uses: NuGet/setup-nuget@v1.0.2
       with:
         nuget-version: latest
+
+    - name: add package repository
+      if: github.event_name == 'push' && github.ref == 'refs/heads/develop'
+      run: nuget source Add -Config ./SharpHelpers/SharpHelpers/nuget.config -Name "github" -Source https://nuget.pkg.github.com/sharpcode-it/index.json -UserName iscifoni -Password ${{ secrets.GITHUB_TOKEN }} -StorePasswordInClearText
+
+    - name: Publish nuget to GitHub Packages
+      if: github.event_name == 'push' && github.ref == 'refs/heads/develop'
+      run: |
+          for f in ./SharpHelpers/SharpHelpers/bin/Release/*.nupkg
+          do
+            curl --silent --show-error --fail -vX PUT -u "iscifoni:${{ secrets.GITHUB_TOKEN }}" -F package=@$f https://nuget.pkg.github.com/shaprcode-it/
+            if [ $? -eq 0 ]
+            then
+              echo "successfully pushed $f"
+            else
+              echo "failed to push $f" >&2
+              exit 1
+            fi
+          done
+          
+      shell: bash
